<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class FeatureSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         // Disable foreign key checks for a clean seed
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Truncate the table to start fresh
        //DB::table('feature_settings')->truncate();

        // Insert the data into the feature_settings table
        DB::table('feature_settings')->insert([
            [
                'id' => 2,
                'slug' => 'capacity-up-to-12-people',
                'name' => 'Capacity: Up to 12 people',
                'description' => null,
                'icon' => 'fas fa-users',
                'status' => 1,
                'created_at' => '2025-06-02 12:09:53',
                'updated_at' => '2025-06-02 12:09:53',
            ],
            [
                'id' => 3,
                'slug' => 'high-speed-wi-fi',
                'name' => 'High-Speed Wi-Fi',
                'description' => null,
                'icon' => 'fas fa-wifi',
                'status' => 1,
                'created_at' => '2025-06-02 12:10:29',
                'updated_at' => '2025-06-02 12:10:29',
            ],
            [
                'id' => 4,
                'slug' => 'video-conferencing-system',
                'name' => 'Video Conferencing System',
                'description' => null,
                'icon' => 'fas fa-video',
                'status' => 1,
                'created_at' => '2025-06-02 12:11:09',
                'updated_at' => '2025-06-02 12:11:09',
            ],
            [
                'id' => 5,
                'slug' => 'comfortable-seating',
                'name' => 'Comfortable Seating',
                'description' => null,
                'icon' => 'fas fa-chair',
                'status' => 1,
                'created_at' => '2025-06-02 12:12:20',
                'updated_at' => '2025-06-02 12:12:20',
            ],
            [
                'id' => 6,
                'slug' => 'good-lighting',
                'name' => 'Good Lighting',
                'description' => null,
                'icon' => 'fas fa-lightbulb',
                'status' => 1,
                'created_at' => '2025-06-02 12:12:51',
                'updated_at' => '2025-06-02 12:12:51',
            ],
            [
                'id' => 7,
                'slug' => 'refreshments-available',
                'name' => 'Refreshments Available',
                'description' => null,
                'icon' => 'fas fa-coffee',
                'status' => 1,
                'created_at' => '2025-06-02 12:13:20',
                'updated_at' => '2025-06-02 12:13:20',
            ],
            [
                'id' => 8,
                'slug' => 'power-outlets-accessible',
                'name' => 'Power Outlets Accessible',
                'description' => null,
                'icon' => 'fas fa-plug',
                'status' => 1,
                'created_at' => '2025-06-02 12:13:47',
                'updated_at' => '2025-06-02 12:13:47',
            ],
            [
                'id' => 9,
                'slug' => 'whiteboard-included',
                'name' => 'Whiteboard Included',
                'description' => null,
                'icon' => 'fas fa-chalkboard',
                'status' => 1,
                'created_at' => '2025-06-02 12:14:25',
                'updated_at' => '2025-06-02 12:14:25',
            ],
            [
                'id' => 10,
                'slug' => 'private-confidential',
                'name' => 'Private & Confidential',
                'description' => null,
                'icon' => 'fas fa-shield-alt',
                'status' => 1,
                'created_at' => '2025-06-02 12:14:53',
                'updated_at' => '2025-06-02 12:14:53',
            ],
            [
                'id' => 11,
                'slug' => 'air-conditioned',
                'name' => 'Air Conditioned',
                'description' => null,
                'icon' => 'fas fa-air-conditioner',
                'status' => 1,
                'created_at' => '2025-06-02 12:17:01',
                'updated_at' => '2025-06-02 12:17:01',
            ],
            [
                'id' => 12,
                'slug' => 'whiteboard-markers',
                'name' => 'Whiteboard & Markers',
                'description' => null,
                'icon' => 'fas fa-chalkboard',
                'status' => 1,
                'created_at' => '2025-06-02 12:17:35',
                'updated_at' => '2025-06-02 12:17:35',
            ],
            [
                'id' => 13,
                'slug' => 'on-site-support-available',
                'name' => 'On-site Support Available',
                'description' => null,
                'icon' => 'fas fa-headset',
                'status' => 1,
                'created_at' => '2025-06-02 12:17:58',
                'updated_at' => '2025-06-02 12:17:58',
            ],
            [
                'id' => 14,
                'slug' => 'complimentary-refreshments',
                'name' => 'Complimentary Refreshments',
                'description' => null,
                'icon' => 'fas fa-coffee',
                'status' => 1,
                'created_at' => '2025-06-02 12:18:30',
                'updated_at' => '2025-06-02 12:18:30',
            ],
            [
                'id' => 15,
                'slug' => 'large-hd-display-screen',
                'name' => 'Large HD Display Screen',
                'description' => null,
                'icon' => 'fas fa-desktop',
                'status' => 1,
                'created_at' => '2025-06-02 12:18:54',
                'updated_at' => '2025-06-02 12:18:54',
            ],
            [
                'id' => 16,
                'slug' => 'capacity-up-to-4-people',
                'name' => 'Capacity: Up to 4 people',
                'description' => null,
                'icon' => 'fas fa-users',
                'status' => 1,
                'created_at' => '2025-06-02 12:19:28',
                'updated_at' => '2025-06-02 12:19:28',
            ],
            [
                'id' => 17,
                'slug' => 'prestigious-business-address',
                'name' => 'Prestigious Business Address',
                'description' => 'Establish your company in a prime business location',
                'icon' => 'fas fa-map-marked-alt',
                'status' => 1,
                'created_at' => '2025-06-03 23:53:34',
                'updated_at' => '2025-06-03 23:53:34',
            ],
            [
                'id' => 18,
                'slug' => 'mail-receiving',
                'name' => 'Mail Receiving',
                'description' => 'Secure handling of all your incoming mail and packages.',
                'icon' => 'fas fa-mail-bulk',
                'status' => 1,
                'created_at' => '2025-06-03 23:55:17',
                'updated_at' => '2025-06-03 23:55:17',
            ],
            [
                'id' => 19,
                'slug' => 'weekly-mail-forwarding',
                'name' => 'Weekly Mail Forwarding',
                'description' => 'Convenient forwarding of your mail to your preferred address.',
                'icon' => 'fas fa-shipping-fast',
                'status' => 1,
                'created_at' => '2025-06-03 23:56:01',
                'updated_at' => '2025-06-03 23:56:01',
            ],
            [
                'id' => 20,
                'slug' => 'mail-scanning-10-pagesmonth',
                'name' => 'Mail Scanning (10 pages/month)',
                'description' => 'Digital copies of your important mail sent directly to you.',
                'icon' => 'fas fa-mail-bulk',
                'status' => 1,
                'created_at' => '2025-06-03 23:56:59',
                'updated_at' => '2025-06-03 23:56:59',
            ],
            [
                'id' => 21,
                'slug' => 'discounted-meeting-rooms',
                'name' => 'Discounted Meeting Rooms',
                'description' => 'Access professional meeting spaces at reduced rates',
                'icon' => 'fas fa-users',
                'status' => 1,
                'created_at' => '2025-06-03 23:57:52',
                'updated_at' => '2025-06-03 23:57:52',
            ],
            [
                'id' => 22,
                'slug' => 'local-phone-number-optional',
                'name' => 'Local Phone Number (Optional)',
                'description' => 'Add a local phone line for a complete business presence.',
                'icon' => 'fas fa-phone',
                'status' => 1,
                'created_at' => '2025-06-03 23:58:33',
                'updated_at' => '2025-06-03 23:58:33',
            ],
            [
                'id' => 23,
                'slug' => 'dedicated-phone-line-answering',
                'name' => 'Dedicated Phone Line & Answering',
                'description' => 'Add a local phone line  and answering for a complete business presence.',
                'icon' => 'fas fa-phone',
                'status' => 1,
                'created_at' => '2025-06-04 00:00:01',
                'updated_at' => '2025-06-04 00:00:01',
            ],
            [
                'id' => 24,
                'slug' => 'mail-scanning-50-pagesmonth',
                'name' => 'Mail Scanning (50 pages/month)',
                'description' => 'Digital copies of your important mail sent directly to you.',
                'icon' => 'fas fa-mail-bulk',
                'status' => 1,
                'created_at' => '2025-06-04 00:00:51',
                'updated_at' => '2025-06-04 00:00:51',
            ],
            [
                'id' => 25,
                'slug' => 'daily-mail-forwarding',
                'name' => 'Daily Mail Forwarding',
                'description' => 'Convenient sorting and forwarding of your mail to your preferred address.',
                'icon' => 'fas fa-mail-bulk',
                'status' => 1,
                'created_at' => '2025-06-04 00:02:06',
                'updated_at' => '2025-06-04 00:02:06',
            ],
            [
                'id' => 26,
                'slug' => 'mail-forwarding-pay-per-use',
                'name' => 'Mail Forwarding (Pay per use)',
                'description' => 'Convenient forwarding of your mail to your preferred address.',
                'icon' => 'fas fa-envelope',
                'status' => 1,
                'created_at' => '2025-06-04 00:03:23',
                'updated_at' => '2025-06-04 00:03:23',
            ],
            [
                'id' => 27,
                'slug' => 'mail-scanning-pay-per-use',
                'name' => 'Mail Scanning (Pay per use)',
                'description' => 'Digital copies of your important mail sent directly to you.',
                'icon' => 'fas fa-mail-bulk',
                'status' => 1,
                'created_at' => '2025-06-04 00:04:39',
                'updated_at' => '2025-06-04 00:04:39',
            ],
            [
                'id' => 28,
                'slug' => 'meeting-room-access-included-hours',
                'name' => 'Meeting Room Access (Included Hours)',
                'description' => 'Access professional meeting spaces at reduced rates.',
                'icon' => 'fas fa-users',
                'status' => 1,
                'created_at' => '2025-06-04 00:23:37',
                'updated_at' => '2025-06-04 00:23:37',
            ],
            [
                'id' => 29,
                'slug' => 'meeting-room-access-discounted',
                'name' => 'Meeting Room Access (Discounted)',
                'description' => 'Access professional meeting spaces at reduced rates.',
                'icon' => 'fas fa-users',
                'status' => 1,
                'created_at' => '2025-06-04 00:24:28',
                'updated_at' => '2025-06-04 00:24:28',
            ],
            [
                'id' => 30,
                'slug' => 'capacity-up-to-20-people',
                'name' => 'Capacity: Up to 20 people',
                'description' => null,
                'icon' => 'fas fa-users',
                'status' => 1,
                'created_at' => '2025-06-04 11:14:57',
                'updated_at' => '2025-06-04 11:14:57',
            ],
            [
                'id' => 31,
                'slug' => 'capacity-up-to-15-people',
                'name' => 'Capacity: Up to 15 people',
                'description' => null,
                'icon' => 'fas fa-users',
                'status' => 1,
                'created_at' => '2025-06-04 11:17:37',
                'updated_at' => '2025-06-04 11:17:37',
            ],
            [
                'id' => 32,
                'slug' => 'capacity-up-to-6-people',
                'name' => 'Capacity: Up to 6 people',
                'description' => null,
                'icon' => 'fas fa-users',
                'status' => 1,
                'created_at' => '2025-06-04 11:30:39',
                'updated_at' => '2025-06-04 11:30:39',
            ],
            [
                'slug' => 'capacity-up-to-2-people',
                'name' => 'Capacity: Up to 2 people',
                'description' => null,
                'icon' => 'fas fa-users',
                'status' => 1,
                'created_at' => '2025-06-04 11:35:01',
                'updated_at' => '2025-06-04 11:35:01',
            ],
        ]);

        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
